[AutoRun]
enabled=false
program=

[BitTorrent]
Session\CreateTorrentSubfolder=true
Session\DisableAutoTMMByDefault=true
Session\DisableAutoTMMTriggers\CategoryChanged=false
Session\DisableAutoTMMTriggers\CategorySavePathChanged=true
Session\DisableAutoTMMTriggers\DefaultSavePathChanged=true
Session\AsyncIOThreadsCount=4
Session\ChokingAlgorithm=FixedSlots
Session\DiskCacheSize=128
Session\DiskCacheTTL=120
Session\DiskIOType=Posix
Session\MaxConnections=300
Session\MaxConnectionsPerTorrent=75
Session\MaxUploads=20
Session\MaxUploadsPerTorrent=4
Session\Preallocation=true
Session\SeedChokingAlgorithm=FastestUpload
Session\SendBufferLowWatermark=256
Session\SendBufferWatermark=1024
Session\SendBufferWatermarkFactor=150
Session\uTPMixedMode=TCP

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Network]
Cookies=@Invalid()

[Preferences]
Bittorrent\AddTrackers=false
Bittorrent\MaxConnecs=300
Bittorrent\MaxConnecsPerTorrent=75
Bittorrent\MaxRatioAction=0
Bittorrent\PeX=true
##uploadThrottleLine
Downloads\PreAllocation=true
Downloads\DiskWriteCacheSize=128
Downloads\DiskWriteCacheTTL=120
Downloads\SavePath=/home/##username/data/
Downloads\TempPath=/home/##username/data/temp/
General\UseRandomPort=true
Queueing\QueueingEnabled=false
WebUI\Address=127.0.0.1
WebUI\AlternativeUIEnabled=false
WebUI\AuthSubnetWhitelist=@Invalid()
WebUI\AuthSubnetWhitelistEnabled=false
WebUI\CSRFProtection=false
WebUI\ClickjackingProtection=false
WebUI\HTTPS\Enabled=false
WebUI\HostHeaderValidation=false
WebUI\LocalHostAuth=true
WebUI\Port=##port
WebUI\UseUPnP=true
WebUI\Username=##username
