[Slice]
CPUAccounting=yes
IOAccounting=yes
MemoryAccounting=yes

# v2 controllers
CPUWeight=%%USER_CPUWEIGHT%%
IOWeight=%%USER_IOWEIGHT%%
TasksMax=%%TASKS_MAX%%
MemoryHigh=%%USER_MEMORY_HIGH%%M
MemoryMax=%%USER_MEMORY_MAX%%M

