[Slice]
CPUAccounting=yes
IOAccounting=yes
BlockIOAccounting=yes
MemoryAccounting=yes

CPUWeight=%%USER_CPUWEIGHT%%
TasksMax=%%TASKS_MAX%%

# v1 blkio controller uses weights; IOWeight retained for parity though effect differs
MemoryHigh=%%USER_MEMORY_HIGH%%M
MemoryMax=%%USER_MEMORY_MAX%%M

