[Slice]
CPUAccounting=yes
IOAccounting=yes
BlockIOAccounting=yes
MemoryAccounting=yes

CPUWeight=%%USER_CGROUP_CPU_WEIGHT%%
IOWeight=%%USER_CGROUP_IO_WEIGHT%%
BlockIOWeight=%%USER_CGROUP_IO_WEIGHT%%
TasksMax=%%USER_CGROUP_TASKS_MAX%%
MemoryHigh=%%USER_CGROUP_MEMORY_HIGH%%M
MemoryMax=%%USER_CGROUP_MEMORY_MAX%%M
CPUQuota=%%USER_CGROUP_CPU_QUOTA%%
